### PR TITLE
update analyse url

### PR DESCRIPTION
**Pull request by noorulh06**

### CODE REVIEW

**Comment by noorulh06** [comment]
This is a small change but it will help a lot of folks to find the correct URL. So Please approve and merge this PR.

**Review by alexander-akait — APPROVED** [review]

**Comment by noorulh06** [comment]
when this PR is going to merge and who is gonna do that?

**Comment by clay-curry** [comment]
when this PR is going to merge and who is gonna do that?

**Comment by clay-curry** [comment]
Seconding what @noorulh06 said. Both the README and the official project description contain broken URLs and need to be updated to [https://webpack.github.io/analyse/](https://webpack.github.io/analyse/). Thank you for this amazing work!

@noorulh06 @alexander-akait @paulirish @sapegin

**Review by alexander-akait — APPROVED** [review]

**Pull request merged**
