### PR TITLE
sort modules by size in chunk view

### PR DESCRIPTION
**Pull request by clarkbynum**
Addresses #28

### CODE REVIEW

**Comment by davityavryan** [comment]
Merge? When?

**Comment by sh3nan1gans** [comment]
@a-r-d  - is there anything I can do to help merge this?

**Comment by a-r-d** [comment]
@sh3nan1gans I would merge this for you, but I'm no longer the maintainer for this repo. I'm not sure who is actually.

**Comment by sh3nan1gans** [comment]
@sokra - can we merge this?

**Pull request closed without merging**
