### PR TITLE
Sort by module size

### PR DESCRIPTION
**Pull request by schnerd**
Added some quick code to support sorting by module size. If this just seems like extra cruft–feel free to close this PR (my feelings will not be hurt). Just thought I'd offer it up in case anyone finds it useful.

### CODE REVIEW

**Comment by wmertens** [comment]
:+1: this would be useful

**Comment by dougalg** [comment]
I would like to see this merged. Is there any further work needed for this?

**Comment by mojoaxel** [comment]
any update on this?

**Comment by a-r-d** [comment]
Hi @sokra is there a maintainer for this project? This would be a nice feature to have.

**Comment by TheLarkInn** [comment]
I'll see if I can get around to this PR. 


@sokra this team-based write-access?

**Comment by Urthen** [comment]
This PR just hit one year old! Let's celebrate it's birthday by merging it, @sokra! 😉

**Comment by TheLarkInn** [comment]
Omg haha. How clever. @sokra has been on vacation and he might not be back quite yet. I'll followup on this. Please ping me by Monday if you don't hear anything.

**Comment by patrickkettner** [comment]
ping

**Comment by sokra** [comment]
Somebody here wants to become a maintainer?

**Comment by Urthen** [comment]
I can assist maintaining if you want.

**Comment by a-r-d** [comment]
@sokra I would not mind helping out

**Comment by Urthen** [comment]
I can help maintain if you want.

On Mon, Oct 24, 2016, 18:42 Tobias Koppers <notifications@github.com> wrote:

Somebody here wants to become a maintainer?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/webpack/analyse/pull/16#issuecomment-255896661>, or mute
the thread

**Comment by sokra** [comment]
You only need to care for fixes or small improvements. On the long run it's the plan to write a complete new analyse tool.

**Comment by a-r-d** [comment]
@sokra got it, I understand. I have tested this branch already so I will go ahead and merge it now. Thanks!

**Pull request merged**
